# PyTorch Training Parameters
model:
  backbone_arch: dinov2_vitb14
  backbone_config: 
    num_trainable_blocks: 2
    return_token: True
    norm_layer: True
    domain_prompt: "none"
    num_clusters: 16
    cluster_dim: 16
    token_dim: 256
    dropout: 0.3
    divide: 1
    shared_clusters: 0
    multi_scale: "1"
  agg_arch: DomainQueriesSALAD
  agg_config:
    num_channels: 768
    num_clusters: 63
    cluster_dim: 128
    token_dim: 256
    dropout: 0.3
    divide: 3
    shared_clusters: 0
    num_queries: 63

datasets:
  train_datasets: 
    - SF_XL
    - GSV
    - mapillary_sls
  val_datasets: 
    - pitts30k
    - pitts250k
    - mapillary_sls
    - svox
    - SF_XL
  test_datasets:
    - pitts30k
    - pitts250k
    - mapillary_sls
    - svox
    - tokyo247
    - SPED
    - nordland
    - nordland_subset
    - amstertime
    - eynsham
  target_val_dataset: mapillary_sls
training:
  num_epochs: 64
  train_batch_size: 30
  test_batch_size: 256
  img_per_place: 4
  num_workers: 4
  sampled_similar_places: 15
  num_processes: 20
  num_batches: 4000
  train_image_size: [224, 224]
  test_image_size: [322, 322]
  optimizer:
    name: AdamW
    lr: 6e-5
    weight_decay: 9.5e-9
    momentum: 0.9
  scheduler:
    name: linear
    args:
      start_factor: 1
      end_factor: 0.2
      total_iters: 4000
  loss:
    name: 'MultiSimilarityLoss'
  miner:
    name: 'MultiSimilarityMiner'
    margin: 0.1
  faiss_gpu: False
  recompute_clusters: True
  prefetch_factor: 1
  recompute_desc: True
  recompute_interval: 4
  cross_loss: False
  cross_loss_weight: 1.0