# PyTorch Training Parameters
model:
  backbone_arch: dinov2_vitb14
  backbone_config: 
    num_trainable_blocks: 4
    return_token: True
    norm_layer: True
  agg_arch: SALAD
  agg_config:
    num_channels: 768
    num_clusters: 64
    cluster_dim: 128
    token_dim: 256

datasets:
  train_datasets: 
    - GSV
    - pitts250k
  val_datasets: 
    - pitts30k
    - pitts250k
    - mapillary_sls
    - svox
  test_datasets:
    - pitts30k
    - pitts250k
    - mapillary_sls
    - svox
    - tokyo247
    - SPED
    - nordland
    - nordland_subset
    - amstertime
    - eynsham
  target_val_dataset: mapillary_sls
training:
  num_epochs: 30
  batch_size: 30
  num_workers: 12
  image_size: [224, 224]
  optimizer:
    name: AdamW
    lr: 6e-5
    weight_decay: 9.5e-9
    momentum: 0.9
  scheduler:
    name: linear
    args:
      start_factor: 1
      end_factor: 0.2
      total_iters: 30
  loss:
    name: 'MultiSimilarityLoss'
  miner:
    name: 'MultiSimilarityMiner'
    margin: 0.1
  faiss_gpu: False
