# Dataset Training Parameters
training:
  available: True
  shuffle_all: False
  random_sample_from_each_place: True
  show_data_stats: True
  GSV_TRAIN_CITIES:
    - 'Bangkok'
    - 'BuenosAires'
    - 'LosAngeles'
    - 'MexicoCity'
    - 'OSL'
    - 'Rome'
    - 'Barcelona'
    - 'Chicago'
    - 'Madrid'
    - 'Miami'
    - 'Phoenix'
    - 'TRT'
    - 'Boston'
    - 'Lisbon'
    - 'Medellin'
    - 'Minneapolis'
    - 'PRG'
    - 'WashingtonDC'
    - 'Brussels'
    - 'London'
    - 'Melbourne'
    - 'Osaka'
    - 'PRS'
validation:
  available: False
test:
  available: False
  