# Dataset Training Parameters
training:
  available: True
  clique_args:
    same_place_threshold: 25.0
    num_batches: 1000
    num_processes: 10
    sampled_similar_places: 5
    cluster_resolution: 20.0
validation:
  available: True
test:
  available: True
  