# Dataset Training Parameters
training:
  available: True
  clique_args:
    same_place_threshold: 25.0
    num_batches: 2000
    num_processes: 10
    sampled_similar_places: 15
    cluster_k: 50
validation:
  available: True
test:
  available: True
  